// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMWmiAykccjXup4cftBfOHzzchUZRWdbw',
    appId: '1:881402332469:web:2b04359d1928ddb380387c',
    messagingSenderId: '881402332469',
    projectId: 'safe-walk1',
    authDomain: 'safe-walk1.firebaseapp.com',
    storageBucket: 'safe-walk1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDaNNEfa8wqUZbfcsvhThuFo6MDDyTql5k',
    appId: '1:881402332469:android:056d12a728c1f26a80387c',
    messagingSenderId: '881402332469',
    projectId: 'safe-walk1',
    storageBucket: 'safe-walk1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDZ3Pn9OlrlXLMj_pViaE7pf3_nqizwec',
    appId: '1:881402332469:ios:67cbe5c5acf1b9d780387c',
    messagingSenderId: '881402332469',
    projectId: 'safe-walk1',
    storageBucket: 'safe-walk1.firebasestorage.app',
    iosBundleId: 'com.example.safewalk',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDZ3Pn9OlrlXLMj_pViaE7pf3_nqizwec',
    appId: '1:881402332469:ios:67cbe5c5acf1b9d780387c',
    messagingSenderId: '881402332469',
    projectId: 'safe-walk1',
    storageBucket: 'safe-walk1.firebasestorage.app',
    iosBundleId: 'com.example.safewalk',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAMWmiAykccjXup4cftBfOHzzchUZRWdbw',
    appId: '1:881402332469:web:128aec2431870d6a80387c',
    messagingSenderId: '881402332469',
    projectId: 'safe-walk1',
    authDomain: 'safe-walk1.firebaseapp.com',
    storageBucket: 'safe-walk1.firebasestorage.app',
  );
}
